import type { Sponsor } from './sponsors';
import type { TeamMember } from './team';
import type { Club } from './types';

/**
 * Demo content for previewing the site before the real data exists.
 *
 * Used automatically whenever Supabase is not configured. The moment you add
 * your Supabase keys, every one of these is replaced by real database rows and
 * none of this reaches production. Artwork lives in public/demo and is
 * generated, not licensed, so there is nothing to attribute.
 *
 * To force the empty "announced soon" states while previewing, set
 * NEXT_PUBLIC_SHOW_DEMO_EVENTS=false in .env.local.
 */

const now = '2026-08-01T10:00:00+05:30';

export const DEMO_CLUBS: Club[] = [
  {
    id: 'VT26_CLUB_001',
    school: 'CENTRAL',
    club_index: 1,
    name: 'Entrepreneurship Club',
    tagline: 'Fostering startup founders, business strategy & innovation',
    logo_url: null,
    contact_name: 'Core Lead',
    contact_email: 'entrepreneurship@vitap.ac.in',
    contact_phone: null,
    instagram: '@ecell.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SAS_002',
    school: 'SAS',
    club_index: 2,
    name: 'American Chemical Society Students Chapter',
    tagline: 'Chemistry research, materials science & chemical engineering',
    logo_url: null,
    contact_name: 'ACS Lead',
    contact_email: 'acs@vitap.ac.in',
    contact_phone: null,
    instagram: '@acs.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_003',
    school: 'SCOPE',
    club_index: 3,
    name: 'Team Next Nexus',
    tagline: 'Next-generation software systems, cloud computing & devops',
    logo_url: null,
    contact_name: 'Nexus Lead',
    contact_email: 'nextnexus@vitap.ac.in',
    contact_phone: null,
    instagram: '@nexus.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_004',
    school: 'SCOPE',
    club_index: 4,
    name: "Women Innovator's Network",
    tagline: 'Empowering women leaders in technology & research',
    logo_url: null,
    contact_name: 'WIN Lead',
    contact_email: 'win@vitap.ac.in',
    contact_phone: null,
    instagram: '@win.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_005',
    school: 'SCOPE',
    club_index: 5,
    name: 'Open Source Community',
    tagline: 'Open source contributions, FOSS & developer collaboration',
    logo_url: null,
    contact_name: 'FOSS Lead',
    contact_email: 'opensource@vitap.ac.in',
    contact_phone: null,
    instagram: '@osc.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_006',
    school: 'SCOPE',
    club_index: 6,
    name: 'Microsoft Student Chapter',
    tagline: 'Building with Azure, .NET & Microsoft tech ecosystem',
    logo_url: null,
    contact_name: 'MSC Lead',
    contact_email: 'msc@vitap.ac.in',
    contact_phone: null,
    instagram: '@msc.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_007',
    school: 'SCOPE',
    club_index: 7,
    name: 'Institute of Engineers (India) Students’ Chapter – CSE',
    tagline: 'Computer science technical workshops & engineering excellence',
    logo_url: null,
    contact_name: 'IEI Lead',
    contact_email: 'iei.cse@vitap.ac.in',
    contact_phone: null,
    instagram: '@iei.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_008',
    school: 'SCOPE',
    club_index: 8,
    name: 'The Node – Blockchain Club',
    tagline: 'Web3, smart contracts, dApps & decentralized networks',
    logo_url: null,
    contact_name: 'Node Lead',
    contact_email: 'node@vitap.ac.in',
    contact_phone: null,
    instagram: '@node.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_009',
    school: 'SCOPE',
    club_index: 9,
    name: 'Machine Learning Club',
    tagline: 'Deep learning algorithms, neural networks & predictive modeling',
    logo_url: null,
    contact_name: 'ML Lead',
    contact_email: 'ml@vitap.ac.in',
    contact_phone: null,
    instagram: '@ml.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_010',
    school: 'SCOPE',
    club_index: 10,
    name: 'ACM Student Chapter',
    tagline: 'Computer science theory, algorithms & competitive programming',
    logo_url: null,
    contact_name: 'ACM Lead',
    contact_email: 'acm@vitap.ac.in',
    contact_phone: null,
    instagram: '@acm.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_011',
    school: 'SCOPE',
    club_index: 11,
    name: 'Innovators Quest Club',
    tagline: 'Creative problem solving, hackathons & prototype sprints',
    logo_url: null,
    contact_name: 'Quest Lead',
    contact_email: 'iqc@vitap.ac.in',
    contact_phone: null,
    instagram: '@iqc.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_012',
    school: 'SCOPE',
    club_index: 12,
    name: 'Intelligent and Intuitive AI Club',
    tagline: 'Intuitive AI agent architectures & generative AI models',
    logo_url: null,
    contact_name: 'AI Lead',
    contact_email: 'iiAI@vitap.ac.in',
    contact_phone: null,
    instagram: '@iiai.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_VSB_003',
    school: 'VSB',
    club_index: 3,
    name: 'Bulls & Bears Club',
    tagline: 'Stock markets, trading strategies & financial analytics',
    logo_url: null,
    contact_name: 'Finance Lead',
    contact_email: 'bullsbears@vitap.ac.in',
    contact_phone: null,
    instagram: '@bullsbears.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_013',
    school: 'SCOPE',
    club_index: 13,
    name: 'Geeks for Geeks VIT-AP Student Chapter',
    tagline: 'Data structures, coding challenges & tech interview prep',
    logo_url: null,
    contact_name: 'GFG Lead',
    contact_email: 'gfg@vitap.ac.in',
    contact_phone: null,
    instagram: '@gfg.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_014',
    school: 'SCOPE',
    club_index: 14,
    name: 'Data Science Club',
    tagline: 'Big data analytics, data visualization & statistical insights',
    logo_url: null,
    contact_name: 'DS Lead',
    contact_email: 'datascience@vitap.ac.in',
    contact_phone: null,
    instagram: '@dsc.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_015',
    school: 'SCOPE',
    club_index: 15,
    name: 'Null Chapter',
    tagline: 'Cybersecurity, penetration testing, CTFs & ethical hacking',
    logo_url: null,
    contact_name: 'Null Lead',
    contact_email: 'null@vitap.ac.in',
    contact_phone: null,
    instagram: '@null.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_VSELL_001',
    school: 'VSL',
    club_index: 1,
    name: 'Milestone Club',
    tagline: 'Leadership, public speaking & interpersonal communication',
    logo_url: null,
    contact_name: 'Milestone Lead',
    contact_email: 'milestone@vitap.ac.in',
    contact_phone: null,
    instagram: '@milestone.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SENSE_002',
    school: 'SENSE',
    club_index: 2,
    name: 'SEDS (Students for the Exploration and Development of Space)',
    tagline: 'Space technology, CubeSats, rocketry & astronomy',
    logo_url: null,
    contact_name: 'SEDS Lead',
    contact_email: 'seds@vitap.ac.in',
    contact_phone: null,
    instagram: '@seds.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SMEC_002',
    school: 'SMEC',
    club_index: 2,
    name: 'DIY Club',
    tagline: 'Hardware tinkering, 3D printing, electronics & maker culture',
    logo_url: null,
    contact_name: 'DIY Lead',
    contact_email: 'diy@vitap.ac.in',
    contact_phone: null,
    instagram: '@diy.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_016',
    school: 'SCOPE',
    club_index: 16,
    name: 'Torque Gaming Club',
    tagline: 'Competitive esports, game development & gaming tournaments',
    logo_url: null,
    contact_name: 'Torque Lead',
    contact_email: 'torque@vitap.ac.in',
    contact_phone: null,
    instagram: '@torquegaming.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SAS_003',
    school: 'SAS',
    club_index: 3,
    name: 'MATH Club',
    tagline: 'Applied mathematics, cryptography & quantitative analysis',
    logo_url: null,
    contact_name: 'Math Lead',
    contact_email: 'math@vitap.ac.in',
    contact_phone: null,
    instagram: '@math.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_017',
    school: 'SCOPE',
    club_index: 17,
    name: 'Women in Open Source (WiOS)',
    tagline: 'Promoting gender diversity & open-source software contributions',
    logo_url: null,
    contact_name: 'WiOS Lead',
    contact_email: 'wios@vitap.ac.in',
    contact_phone: null,
    instagram: '@wios.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_018',
    school: 'SCOPE',
    club_index: 18,
    name: 'Artificial Intelligence Based Productivity Tools (AiBPT) Club',
    tagline: 'AI-assisted workflows, automation scripts & productivity tools',
    logo_url: null,
    contact_name: 'AiBPT Lead',
    contact_email: 'aibpt@vitap.ac.in',
    contact_phone: null,
    instagram: '@aibpt.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_019',
    school: 'SCOPE',
    club_index: 19,
    name: 'Android Club',
    tagline: 'Mobile app development, Kotlin, Jetpack Compose & Android OS',
    logo_url: null,
    contact_name: 'Android Lead',
    contact_email: 'android@vitap.ac.in',
    contact_phone: null,
    instagram: '@android.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_VSELL_002',
    school: 'VSL',
    club_index: 2,
    name: 'Dragon Fist Martial Arts Club',
    tagline: 'Martial arts, self-defense discipline & physical fitness',
    logo_url: null,
    contact_name: 'Martial Lead',
    contact_email: 'dragonfist@vitap.ac.in',
    contact_phone: null,
    instagram: '@dragonfist.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_VSELL_003',
    school: 'VSL',
    club_index: 3,
    name: 'Mélange',
    tagline: 'Music, dance, performing arts & multi-cultural harmony',
    logo_url: null,
    contact_name: 'Melange Lead',
    contact_email: 'melange@vitap.ac.in',
    contact_phone: null,
    instagram: '@melange.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_020',
    school: 'SCOPE',
    club_index: 20,
    name: 'CodeChef VIT-AP Chapter',
    tagline: 'Competitive programming, speed coding & contest preparation',
    logo_url: null,
    contact_name: 'CodeChef Lead',
    contact_email: 'codechef@vitap.ac.in',
    contact_phone: null,
    instagram: '@codechef.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_021',
    school: 'SCOPE',
    club_index: 21,
    name: 'Google Developer Groups, VIT-AP (GDGoC VIT-AP)',
    tagline: 'Google Cloud, Android, Flutter & AI development community',
    logo_url: null,
    contact_name: 'GDGoC Lead',
    contact_email: 'gdgoc@vitap.ac.in',
    contact_phone: null,
    instagram: '@gdgoc.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_022',
    school: 'SCOPE',
    club_index: 22,
    name: 'Graphical Processing Unit Group (GPUG Club)',
    tagline: 'GPU programming, CUDA, parallel computing & graphics',
    logo_url: null,
    contact_name: 'GPUG Lead',
    contact_email: 'gpug@vitap.ac.in',
    contact_phone: null,
    instagram: '@gpug.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_VSELL_004',
    school: 'VSL',
    club_index: 4,
    name: 'KNIT Club',
    tagline: 'Creative crafts, textile arts & hands-on design studio',
    logo_url: null,
    contact_name: 'KNIT Lead',
    contact_email: 'knit@vitap.ac.in',
    contact_phone: null,
    instagram: '@knit.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_VSELL_005',
    school: 'VSL',
    club_index: 5,
    name: 'Laetitia',
    tagline: 'Literary arts, creative writing, debate & poetry',
    logo_url: null,
    contact_name: 'Laetitia Lead',
    contact_email: 'laetitia@vitap.ac.in',
    contact_phone: null,
    instagram: '@laetitia.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_VSELL_006',
    school: 'VSL',
    club_index: 6,
    name: 'MUN Club',
    tagline: 'Model United Nations, international diplomacy & debate',
    logo_url: null,
    contact_name: 'MUN Lead',
    contact_email: 'mun@vitap.ac.in',
    contact_phone: null,
    instagram: '@mun.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_VSELL_007',
    school: 'VSL',
    club_index: 7,
    name: 'Rotaract Club of VIT-AP University',
    tagline: 'Community service, youth leadership & social impact',
    logo_url: null,
    contact_name: 'Rotaract Lead',
    contact_email: 'rotaract@vitap.ac.in',
    contact_phone: null,
    instagram: '@rotaract.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_023',
    school: 'SCOPE',
    club_index: 23,
    name: 'The Gamers Crib',
    tagline: 'Esports arena, streaming culture & gaming community',
    logo_url: null,
    contact_name: 'Gamers Lead',
    contact_email: 'gamerscrib@vitap.ac.in',
    contact_phone: null,
    instagram: '@gamerscrib.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SAS_004',
    school: 'SAS',
    club_index: 4,
    name: 'UniQuest Club',
    tagline: 'Scientific quizzes, research symposiums & inter-college challenges',
    logo_url: null,
    contact_name: 'UniQuest Lead',
    contact_email: 'uniquest@vitap.ac.in',
    contact_phone: null,
    instagram: '@uniquest.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_024',
    school: 'SCOPE',
    club_index: 24,
    name: 'Drushya Animation and Gaming Club (DAG)',
    tagline: '2D/3D animation, concept art & game asset design',
    logo_url: null,
    contact_name: 'DAG Lead',
    contact_email: 'dag@vitap.ac.in',
    contact_phone: null,
    instagram: '@dag.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_025',
    school: 'SCOPE',
    club_index: 25,
    name: 'OASIS VFX and CGI Club',
    tagline: 'Visual effects, 3D CGI rendering & video post-production',
    logo_url: null,
    contact_name: 'Oasis Lead',
    contact_email: 'oasis@vitap.ac.in',
    contact_phone: null,
    instagram: '@oasis.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_026',
    school: 'SCOPE',
    club_index: 26,
    name: 'Code Crux',
    tagline: 'Algorithmic problem solving, hackathons & code optimization',
    logo_url: null,
    contact_name: 'Crux Lead',
    contact_email: 'codecrux@vitap.ac.in',
    contact_phone: null,
    instagram: '@codecrux.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SENSE_003',
    school: 'SENSE',
    club_index: 3,
    name: 'Geospatial Intelligence Club',
    tagline: 'GIS mapping, satellite remote sensing & spatial data analytics',
    logo_url: null,
    contact_name: 'Geo Lead',
    contact_email: 'geospatial@vitap.ac.in',
    contact_phone: null,
    instagram: '@geo.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SCOPE_027',
    school: 'SCOPE',
    club_index: 27,
    name: 'Python Automation Club (P.A.C.)',
    tagline: 'Python scripting, web scraping, bots & workflow automation',
    logo_url: null,
    contact_name: 'PAC Lead',
    contact_email: 'pac@vitap.ac.in',
    contact_phone: null,
    instagram: '@pac.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SAS_005',
    school: 'SAS',
    club_index: 5,
    name: 'Quantum Frontier Club',
    tagline: 'Quantum computing, quantum algorithms & quantum physics',
    logo_url: null,
    contact_name: 'Quantum Lead',
    contact_email: 'quantum@vitap.ac.in',
    contact_phone: null,
    instagram: '@quantum.vitap',
    is_active: true,
    created_at: now,
  },
  {
    id: 'VT26_SAS_006',
    school: 'SAS',
    club_index: 6,
    name: 'Sci Space Research Club',
    tagline: 'Astrophysics, space science research & celestial observation',
    logo_url: null,
    contact_name: 'Space Lead',
    contact_email: 'scispace@vitap.ac.in',
    contact_phone: null,
    instagram: '@scispace.vitap',
    is_active: true,
    created_at: now,
  },
];

export const DEMO_SPONSORS: Sponsor[] = [
  {
    id: 'demo-sp-1',
    name: 'Northwind Cloud',
    tier: 'title',
    logo_url: '/demo/sponsor-northwind.webp',
    website: 'https://example.com',
    blurb:
      'Presenting partner for V-TAPP 2026, backing the hackathon track and providing cloud credits to every registered team.',
    sort_order: 10,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  { id: 'demo-sp-2', name: 'Aeronix', tier: 'gold', logo_url: '/demo/sponsor-aeronix.webp', website: 'https://example.com', blurb: null, sort_order: 10, is_active: true, created_at: now, updated_at: now },
  { id: 'demo-sp-3', name: 'Quantile Analytics', tier: 'gold', logo_url: '/demo/sponsor-quantile.webp', website: 'https://example.com', blurb: null, sort_order: 20, is_active: true, created_at: now, updated_at: now },
  { id: 'demo-sp-4', name: 'Vertex Labs', tier: 'gold', logo_url: '/demo/sponsor-vertex-labs.webp', website: null, blurb: null, sort_order: 30, is_active: true, created_at: now, updated_at: now },
  { id: 'demo-sp-5', name: 'Kalpana', tier: 'silver', logo_url: '/demo/sponsor-kalpana.webp', website: 'https://example.com', blurb: null, sort_order: 10, is_active: true, created_at: now, updated_at: now },
  { id: 'demo-sp-6', name: 'Stackforge', tier: 'silver', logo_url: '/demo/sponsor-stackforge.webp', website: 'https://example.com', blurb: null, sort_order: 20, is_active: true, created_at: now, updated_at: now },
  { id: 'demo-sp-7', name: 'Meridian', tier: 'bronze', logo_url: '/demo/sponsor-meridian.webp', website: null, blurb: null, sort_order: 10, is_active: true, created_at: now, updated_at: now },
  { id: 'demo-sp-8', name: 'BlueCircuit', tier: 'partner', logo_url: '/demo/sponsor-bluecircuit.webp', website: null, blurb: null, sort_order: 10, is_active: true, created_at: now, updated_at: now },
];

function member(
  id: string,
  name: string,
  role: string,
  department: string,
  sort_order: number,
  extra: Partial<TeamMember> = {}
): TeamMember {
  return {
    id,
    name,
    role,
    department,
    photo_url: null, // the card falls back to initials, which reads fine
    email: null,
    linkedin: null,
    instagram: null,
    sort_order,
    is_active: true,
    created_at: now,
    updated_at: now,
    ...extra,
  };
}

export const DEMO_TEAM: TeamMember[] = [
  member('demo-t-2', 'Dr. Sankar Viswanathan', 'Vice President', 'Vice Presidents', 20, {
    photo_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxLfVD82nycVkvoowu3R2ZCW2btEDnp_bpjNrOFQZzWg&s=10'
  }),
  member('demo-t-3', 'Dr. Sekar Viswanathan', 'Vice President', 'Vice Presidents', 30, {
    photo_url: 'https://vitap.ac.in/_next/image?url=https%3A%2F%2Fvitap-backend.s3.ap-south-1.amazonaws.com%2FDr_Sekar_Viswanathan_15a68c464a.avif&w=640&q=75'
  }),
  member('demo-t-4', 'Dr. G.V.Selvam', 'Vice President', 'Vice Presidents', 40, {
    photo_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHEzradlkwKqKwR-_G9s1weqU6cU2j6GH3EGJkHXJUXg&s=10'
  }),
  member('demo-t-5', 'Dr. Sandhya Pentareddy', 'Executive Director', 'Executive Director', 50, {
    photo_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKaPigtv8h5xz-OGAbyIaJVjyuiAAl7Dw3o1FBLXNk0A&s=10'
  }),
  member('demo-t-new', 'Ms. Kadhambari S Viswanathan', 'Assistant Vice - President', 'Executive Director', 55, {
    photo_url: 'https://vit.ac.in/wp-content/uploads/2024/10/avp-new-1.jpg'
  }),
  member('demo-t-6', 'Dr. P. Arulmozhivarman', 'Vice Chancellor', 'Vice Chancellor & Registrar', 60, {
    photo_url: 'https://vitap.ac.in/_next/image?url=https%3A%2F%2Fvitap-backend.s3.ap-south-1.amazonaws.com%2FDr_P_Arulmozhivarman_VC_3e6b8e2db2.avif&w=640&q=75'
  }),
  member('demo-t-7', 'Dr. Jagadish Chandra Mudiganti', 'Registrar', 'Vice Chancellor & Registrar', 70, {
    photo_url: 'https://vitap.ac.in/_next/image?url=https%3A%2F%2Fvitap-backend.s3.ap-south-1.amazonaws.com%2FDr_JAGADISH_CHANDRAMUDIGANTI_7da6ac0c7d.avif&w=640&q=75'
  }),
  member('demo-t-8', 'Dr. Somya Ranjan Sahoo', 'Convenor, VTAPP 2026', 'Convenor', 80, {
    photo_url: 'https://vitap.ac.in/_next/image?url=https%3A%2F%2Fvitap-backend.s3.ap-south-1.amazonaws.com%2F70167_Dr_Somya_Ranjan_Sahoo_SCOPE_1298_7d2cb16047.avif&w=1920&q=75'
  }),
  member('demo-t-9', 'Dr. Sambhudutta Nanda', 'Co-Convenor', 'Co-Convenors', 90, {
    photo_url: 'https://vitap.ac.in/_next/image?url=https%3A%2F%2Fvitap-backend.s3.ap-south-1.amazonaws.com%2F70514_Dr_Sambhudutta_Nanda_SENSE_1316_7515944399.avif&w=1920&q=75'
  }),
  member('demo-t-10', 'Dr. Gokul Yenduri', 'Co-Convenor', 'Co-Convenors', 100, {
    photo_url: 'https://vitap.ac.in/_next/image?url=https%3A%2F%2Fvitap-backend.s3.ap-south-1.amazonaws.com%2FMr_Gokul_Yenduri_70634_IMG_4973_SCOPE_504ea5823a.avif&w=1920&q=75'
  }),
];
