import type { EventWithClub } from './types';

/**
 * Demo events used ONLY when Supabase env vars are absent, so the site can be
 * previewed / built before the database is wired up. Once
 * NEXT_PUBLIC_SUPABASE_URL is set, real data replaces all of this.
 */
const base = {
  rules: null,
  max_participants: 120,
  registration_url: 'https://forms.gle/example',
  registration_deadline: '2026-09-06T23:59:00+05:30',
  prizes: '1st ₹25,000 · 2nd ₹15,000 · 3rd ₹10,000',
  coordinator_name: 'Event Coordinator',
  coordinator_phone: '+91 90000 00000',
  coordinator_email: 'vtapp.convenor@vitap.ac.in',
  status: 'approved' as const,
  rejection_reason: null,
  created_at: '2025-12-01T10:00:00+05:30',
  updated_at: '2025-12-01T10:00:00+05:30',
  submitted_at: '2025-12-01T10:00:00+05:30',
  reviewed_at: '2025-12-02T10:00:00+05:30',
};

export const SAMPLE_EVENTS: EventWithClub[] = [
  {
    ...base,
    id: 'demo-1',
    poster_url: '/demo/hackaverse.jpg',
    thumbnail_url: '/demo/hackaverse-thumb.webp',
    event_code: 'VT26_SCOPE_001-E01',
    club_id: 'VT26_SCOPE_001',
    school: 'SCOPE',
    slug: 'hackaverse-24h-hackathon',
    title: 'HackaVerse',
    tagline: '24 hours. One problem statement. Zero sleep.',
    description:
      'The flagship hackathon of V-TAPP. Teams get a live problem statement at 9 AM and ship a working prototype by 9 AM the next day. Mentors from industry float through the night, and the top six teams demo on the main stage.',
    category: 'coding',
    mode: 'offline',
    start_at: '2026-09-11T09:00:00+05:30',
    end_at: '2026-09-12T09:00:00+05:30',
    venue: 'AB-1 Central Lab',
    team_type: 'team',
    team_min: 2,
    team_max: 4,
    registration_fee: 300,
    prize_pool: 50000,
    is_featured: true,
    club: { id: 'VT26_SCOPE_001', name: 'Google Developer Group VIT-AP', logo_url: '/demo/club-gdg.webp', instagram: null },
  },
  {
    ...base,
    id: 'demo-2',
    poster_url: '/demo/robowars.jpg',
    thumbnail_url: '/demo/robowars-thumb.webp',
    event_code: 'VT26_SENSE_001-E01',
    club_id: 'VT26_SENSE_001',
    school: 'SENSE',
    slug: 'robowars-arena',
    title: 'RoboWars Arena',
    tagline: 'Build it. Drive it. Watch it get destroyed.',
    description:
      'A 15 kg combat robotics tournament in a fully enclosed arena. Bring your bot, pass the safety inspection, and fight through a double-elimination bracket. Spare parts pit available on site.',
    category: 'robotics',
    mode: 'offline',
    start_at: '2026-09-11T11:00:00+05:30',
    end_at: '2026-09-11T18:00:00+05:30',
    venue: 'Open Air Theatre',
    team_type: 'team',
    team_min: 3,
    team_max: 6,
    registration_fee: 800,
    prize_pool: 75000,
    is_featured: true,
    club: { id: 'VT26_SENSE_001', name: 'IEEE Student Branch', logo_url: '/demo/club-ieee.webp', instagram: null },
  },
  {
    ...base,
    id: 'demo-3',
    poster_url: '/demo/cad-clash.jpg',
    thumbnail_url: '/demo/cad-clash-thumb.webp',
    event_code: 'VT26_SMEC_001-E01',
    club_id: 'VT26_SMEC_001',
    school: 'SMEC',
    slug: 'cad-clash',
    title: 'CAD Clash',
    tagline: 'Model the impossible against the clock.',
    description:
      'A timed CAD modelling contest. Three rounds of increasing difficulty on SolidWorks or Fusion 360, judged on accuracy, feature tree quality and speed. Machines provided.',
    category: 'technical',
    mode: 'offline',
    start_at: '2026-09-11T14:00:00+05:30',
    end_at: '2026-09-11T17:30:00+05:30',
    venue: 'SMEC CAD Lab',
    team_type: 'solo',
    team_min: 1,
    team_max: 1,
    registration_fee: 150,
    prize_pool: 20000,
    is_featured: false,
    club: { id: 'VT26_SMEC_001', name: 'SAE Collegiate Club', logo_url: '/demo/club-sae.webp', instagram: null },
  },
  {
    ...base,
    id: 'demo-4',
    poster_url: '/demo/pitch-perfect.jpg',
    thumbnail_url: '/demo/pitch-perfect-thumb.webp',
    event_code: 'VT26_VSB_001-E01',
    club_id: 'VT26_VSB_001',
    school: 'VSB',
    slug: 'pitch-perfect-startup-battle',
    title: 'Pitch Perfect',
    tagline: 'Ten slides, five minutes, one real cheque.',
    description:
      'A startup pitch battle judged by founders and angel investors. Shortlisted teams pitch live to a panel; the winning team leaves with seed funding and three months of incubation support.',
    category: 'business',
    mode: 'offline',
    start_at: '2026-09-12T10:00:00+05:30',
    end_at: '2026-09-12T16:00:00+05:30',
    venue: 'Auditorium 2',
    team_type: 'team',
    team_min: 2,
    team_max: 5,
    registration_fee: 0,
    prize_pool: 100000,
    is_featured: true,
    club: { id: 'VT26_VSB_001', name: 'E-Cell VIT-AP', logo_url: '/demo/club-ecell.webp', instagram: null },
  },
  {
    ...base,
    id: 'demo-5',
    poster_url: '/demo/bio-hack.jpg',
    thumbnail_url: '/demo/bio-hack-thumb.webp',
    event_code: 'VT26_SAS_001-E01',
    club_id: 'VT26_SAS_001',
    school: 'SAS',
    slug: 'bio-hack-lab',
    title: 'Bio-Hack Lab',
    tagline: 'Wet lab meets dry lab.',
    description:
      'A hands-on workshop on CRISPR design and protein folding prediction, followed by a mini-challenge where teams design a construct in silico and defend it to a panel.',
    category: 'workshop',
    mode: 'offline',
    start_at: '2026-09-12T09:30:00+05:30',
    end_at: '2026-09-12T13:00:00+05:30',
    venue: 'SAS Biotech Lab',
    team_type: 'both',
    team_min: 1,
    team_max: 3,
    registration_fee: 250,
    prize_pool: null,
    is_featured: false,
    club: { id: 'VT26_SAS_001', name: 'Bioverse', logo_url: '/demo/club-bioverse.webp', instagram: null },
  },
  {
    ...base,
    id: 'demo-6',
    poster_url: '/demo/breach.jpg',
    thumbnail_url: '/demo/breach-thumb.webp',
    event_code: 'VT26_SCOPE_002-E01',
    club_id: 'VT26_SCOPE_002',
    school: 'SCOPE',
    slug: 'capture-the-flag',
    title: 'Breach',
    tagline: 'Jeopardy-style CTF. Eight hours. No mercy.',
    description:
      'A jeopardy-format capture-the-flag across web, binary exploitation, forensics, crypto and OSINT. Live scoreboard on the main screen, dynamic scoring, first-blood bonuses.',
    category: 'coding',
    mode: 'offline',
    start_at: '2026-09-12T10:00:00+05:30',
    end_at: '2026-09-12T18:00:00+05:30',
    venue: 'AB-2 Seminar Hall',
    team_type: 'team',
    team_min: 1,
    team_max: 4,
    registration_fee: 0,
    prize_pool: 30000,
    is_featured: false,
    club: { id: 'VT26_SCOPE_002', name: 'Cybernauts', logo_url: '/demo/club-cybernauts.webp', instagram: null },
  },
];
